# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: RubyCon - The Ruby Conference in Italy
info_email: rubycon-organizers@googlegroups.com
# cfp_email: cfp@rubycon.it
site_version: '0.2.14b'

event:
  name: Rubycon
  date: may 8th, 2026
  location: rimini, italy

social_media:
  - name: Facebook
    url: "https://www.facebook.com/rubyconitaly"
    icon: facebook
  - name: Mastodon
    url: "https://mastodon.social/@rubycon"
    icon: mastodon
  - name: Instagram
    url: "https://www.instagram.com/rubyconitaly/"
    icon: instagram
  - name: YouTube
    url: "https://www.youtube.com/channel/UCNqcu--Vp9H7JfGHW4TYzIw"
    icon: youtube
  - name: Discord
    url: "https://discord.gg/T43GHE6wHH"
    icon: discord
  - name: X-twitter
    url: "https://x.com/rubycon2026"
    icon: "x-twitter"
  - name: Bluesky
    url: "https://bsky.app/profile/rubyconitaly.bsky.social"
    icon: bluesky
navigation:
  - name: home
    link: "#home"
  - name: about
    link: "#about"
  - name: speakers
    link: "#speakers"
  - name: schedule
    link: "#schedule"
  - name: venue
    link: "#venue"
  - name: newsletter
    link: "#registration"
  # - name: sponsors
  #   link: "#sponsors"
about:
  - title: ruby at the core
    icon: code
    description: learn about the latest trends and best practices in ruby, rails, and related technologies from industry leaders.
  - title: community connections
    icon: users
    description: meet fellow ruby developers, share ideas, and build relationships with collaborators, employers, and enthusiasts.
  - title: italian atmosphere
    icon: utensils
    description: experience the warmth of Italy through local culture, food, and hospitality while attending the conference in Rimini.
speakers:
  - avatar: '/assets/images/logo/0_0.jpeg'
    full_name: Julius Caesar
    role: senior ruby developer @company
    description: TBD
    keys: [ruby, ruby on rails]
  - avatar: '/assets/images/logo/0_1.jpeg'
    full_name: Julius Caesar
    role: senior ruby developer @company
    description: TBD
    keys: [ruby, ruby on rails]
  - avatar: '/assets/images/logo/0_2.jpeg'
    full_name: Julius Caesar
    role: senior ruby developer @company
    description: TBD
    keys: [ruby, ruby on rails]
schedule:
  - title: 'day 1 - may 8'
    events:
      - clock: '09:00 - 10:00'
        description: 'Check-in & Welcome Coffee'
        full_name: 'All Attendees'
        key: 'Networking'
      - clock: '10:00 - 10:30'
        description: 'Opening Keynote'
        full_name: 'TBD'
        key: 
      - clock: '10:30 - 11:15'
        description: 'First Speech'
        full_name: 'TBD'
        key:
      - clock: '11:15 - 11:30'
        description: 'Coffee Break'
        full_name: 'All Attendees'
        key:
      - clock: '11:30 - 12:15'
        description: 'Second Speech'
        full_name: 'TBD'
        key:
      - clock: '12:15 - 13:00'
        description: 'Third Speech'
        full_name: 'TBD'
        key:
      - clock: '13:00 - 14:30'
        description: 'Lunch Break & Networking'
        full_name: 'All Attendees'
        key:
      - clock: '14:30 - 15:15'
        description: 'Fourth Speech'
        full_name: 'TBD'
        key:
      - clock: '15:15 - 16:00'
        description: 'Fifth Speech'
        full_name: 'TBD'
        key:
      - clock: '16:00 - 16:15'
        description: 'Coffee Break'
        full_name: 'All Attendees'
        key:
      - clock: '16:15 - 17:00'
        description: 'Sixth Speech'
        full_name: 'TBD'
        key:
      - clock: '17:00 - 17:45'
        description: 'Seventh Speech'
        full_name: 'TBD'
        key:
      - clock: '17:45 - 18:00'
        description: "It's a wrap!"
        full_name: 'All Attendees'
        key:
      - clock: '20:00 - 1:00'
        description: "Toga Party!"
        full_name: 'All Attendees'
        key:

# Build settings


github:
  is_project_page: true
  repository_url: 'https://github.com/palladius/rubycon.it'
  repository_name: 'rubycon.it'
  owner_name: 'palladius'
  owner_url: 'https://github.com/palladius'
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
