# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: RubyCon - The Ruby Conference in Italy
info_email: rubycon-organizers@googlegroups.com
# cfp_email: cfp@rubycon.it
site_version: '0.2.14b'

event:
  name: Rubycon
  date: May 8th, 2026
  location: Rimini, Italy

social_media:
  - name: Facebook
    url: "https://www.facebook.com/rubyconitaly"
    icon: "📘"
  - name: X
    url: "https://x.com/rubycon2026"
    icon: "🐦"
  - name: Bluesky
    url: "https://bsky.app/profile/rubyconitaly.bsky.social"
    icon: "🦋"
  - name: Mastodon
    url: "https://mastodon.social/@rubycon"
    icon: "🐘"
  - name: Instagram
    url: "https://www.instagram.com/rubyconitaly/"
    icon: "📸"
  - name: YouTube
    url: "https://www.youtube.com/channel/UCNqcu--Vp9H7JfGHW4TYzIw"
    icon: "📹"
  - name: Discord
    url: "https://discord.gg/T43GHE6wHH"
    icon: "👾"
navigation:
  - name: Home
    link: "#"
  - name: About
    link: "#about"
  - name: Speakers
    link: "#speakers"
  - name: Schedule
    link: "#schedule"
  - name: Venue
    link: "#venue"
  - name: Sponsors
    link: "#sponsors"
about:
  - title: Cutting-edge Content
    icon: code
    description: Learn about the latest trends and best practices in Ruby, Rails, and related technologies from industry leaders.
  - title: Networking
    icon: users
    description: Connect with fellow Ruby enthusiasts, potential collaborators, and employers in Italy's vibrant tech scene.
  - title: Italian Flair
    icon: utensils
    description: Enjoy authentic Italian food, wine, and culture as part of your conference experience in beautiful Florence.

# Build settings


github:
  is_project_page: true
  repository_url: 'https://github.com/palladius/rubycon.it'
  repository_name: 'rubycon.it'
  owner_name: 'palladius'
  owner_url: 'https://github.com/palladius'
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
